# Generated by Django 5.1.6 on 2025-03-13 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_datalookup_data_type_remove_datalookup_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.category', verbose_name='Product Category')),
                ('field_type', models.ForeignKey(limit_choices_to={'type': 'attribute_field_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.datalookup', verbose_name='Field Type')),
                ('form_type', models.ForeignKey(blank=True, limit_choices_to={'type': 'attribute_form_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.datalookup', verbose_name='Form Type')),
            ],
            options={
                'verbose_name': 'Product Category Attribute',
                'verbose_name_plural': 'Product Category Attributes',
                'db_table': 'product_category_attribute',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('available_colors', models.ForeignKey(limit_choices_to={'type': 'product_color_type'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datalookup')),
                ('category', models.ForeignKey(limit_choices_to={'tn_children_pks': ''}, on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='store.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('field_name', models.CharField(max_length=100, verbose_name='Name')),
                ('field_value', models.CharField(max_length=200, verbose_name='Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'db_table': 'product_attribute',
            },
        ),
    ]
