# Generated by Django 5.1.6 on 2025-03-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_datalookup_data_type_remove_datalookup_note_and_more'),
        ('store', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='store.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(limit_choices_to={'type': 'product_color_type'}, null=True, to='core.datalookup'),
        ),
    ]
