# Generated by Django 5.1.6 on 2025-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalookup',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='datalookup',
            name='note',
        ),
        migrations.AlterField(
            model_name='datalookup',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Category'),
        ),
    ]
